### ISSUE TITLE
git hooks

### ISSUE THREAD

**Issue by zhaiyuxin103** [zhaiyuxin103/laravel-skeleton#6]
To Do:

- [x] add [husky](https://github.com/typicode/husky)
- [x] add [lint-staged](https://github.com/lint-staged/lint-staged)
- [x] add [commitlint](https://github.com/conventional-changelog/commitlint)

Commands: 

- [x] npm install --save-dev husky
- [x] npx husky init
- [x] npm install --save-dev lint-staged
- [x] echo "npx lint-staged" > .husky/pre-commit
- [x] echo "export default { \"*.php\": [\"./vendor/bin/pint\"] };" > lint-staged.config.mjs
- [x] npm install --save-dev @commitlint/{cli,config-conventional}
- [x] echo "export default { extends: ['@commitlint/config-conventional'] };" > commitlint.config.mjs
- [x] echo "npx --no -- commitlint --edit \$1" > .husky/commit-msg

Git Commit: 

- [x] build(deps): add husky (#6)
- [x] build(deps): add lint staged (#6)
- [x] build(deps): add commitlint (#6)

参考：

1. https://julweb.dev/blog/git-hooks-in-laravel-with-husky
2. https://typicode.github.io/husky/
3. https://commitlint.js.org/
